// Package protection строит и применяет pf-правила, которые режут трафик
// к защищаемым сетям, когда туннель sshuttle не поднят.
package protect

import (
	"fmt"
	"net/netip"
	"os"
	"sort"
	"strings"

	"github.com/tasticolly/splitr/internal/config"
	"github.com/tasticolly/splitr/internal/pfctl"
)

const (
	// Anchor — имя pf-якоря, в который загружаются правила.
	Anchor = "splitr"
	// AnchorFile — файл, из которого правила подхватываются при загрузке /etc/pf.conf.
	AnchorFile = "/etc/pf.anchors/splitr"
	// AnchorFileEnv переопределяет путь к файлу якоря — нужно тестам
	// и запуску демона без root.
	AnchorFileEnv = "SPLITR_ANCHOR_FILE"
	// PfConf — главный конфиг pf, куда прописывается вызов якоря.
	PfConf = "/etc/pf.conf"

	blockTable = "splitr_block"
	passTable  = "splitr_pass"
	dnsTable   = "splitr_dns"
)

// AnchorFilePath возвращает путь к файлу якоря с учётом переопределения.
func AnchorFilePath() string {
	if custom := os.Getenv(AnchorFileEnv); custom != "" {
		return custom
	}
	return AnchorFile
}

// Ruleset — вычисленный набор сетей для блокировки.
type Ruleset struct {
	Block      []string
	Pass       []string
	DNSServers []string
	// Strict делает блокировку безусловной (quick): её не переопределит даже sshuttle.
	Strict bool
	// Log пишет отброшенные пакеты в pflog0.
	Log bool
}

// Build вычисляет, что блокировать, из конфига и выбранного профиля.
func Build(cfg config.Config, profile config.Profile, strictMode bool) Ruleset {
	routed := cfg.RoutedSubnets(profile)

	// В panic-режиме выбранный режим не важен: смысл panic в том, чтобы
	// перекрыть защищаемые сети немедленно, даже если обычная защита снята.
	mode := cfg.Protection.Mode
	if strictMode && mode == config.ModeOff {
		mode = config.ModeAll
	}

	var block []string
	switch mode {
	case config.ModeOff:
		return Ruleset{}
	case config.ModeCustom:
		block = cfg.Protection.Block
	case config.ModePublic:
		block = publicOnly(routed)
	default:
		block = routed
	}

	// Исключения идут отдельной pass-таблицей: в pf выигрывает последнее
	// совпавшее правило, поэтому pass после block снимает блокировку с LAN.
	pass := append([]string{}, cfg.ExcludedSubnets(profile)...)
	pass = append(pass, cfg.Protection.Allow...)

	rs := Ruleset{
		Block:  dedupe(block),
		Pass:   dedupe(pass),
		Strict: strictMode,
		Log:    cfg.Protection.Log,
	}
	if cfg.Protection.BlockDNS {
		rs.DNSServers = dedupe(cfg.Protection.DNSServers)
	}
	return rs
}

// Empty сообщает, что блокировать нечего.
func (r Ruleset) Empty() bool { return len(r.Block) == 0 && len(r.DNSServers) == 0 }

// Rules рендерит текст правил для pf-якоря.
//
// Блокировка намеренно НЕ помечена quick и ограничена «не lo0»: sshuttle
// заворачивает трафик правилом `pass out route-to lo0 ... to <subnet>`,
// которое стоит в якоре ниже и по правилу last-match-wins перебивает блок.
// Значит правила можно держать загруженными постоянно: пока туннель поднят,
// они не мешают, а как только он исчезает — трафик умирает сразу, без гонки.
func (r Ruleset) Rules() []byte {
	if r.Empty() {
		return []byte("# splitr: protection is off\n")
	}

	var b strings.Builder
	b.WriteString("# Generated by splitr. Manual edits will be overwritten.\n")
	b.WriteString(table(blockTable, r.Block))
	b.WriteString(table(passTable, r.Pass))
	b.WriteString(table(dnsTable, r.DNSServers))

	// В panic-режиме правила помечаются quick, и тогда первое совпадение
	// останавливает разбор — значит исключения обязаны идти до блокировки.
	// В обычном режиме quick нет, выигрывает последнее совпадение, поэтому
	// исключения идут после.
	quick := ""
	if r.Strict {
		quick = "quick "
	}
	logKeyword := ""
	if r.Log {
		logKeyword = "log "
	}
	passRule := ""
	if len(r.Pass) > 0 {
		passRule = fmt.Sprintf("pass out %son ! lo0 inet from any to <%s>\n", quick, passTable)
	}

	if r.Strict {
		b.WriteString(passRule)
	}
	if len(r.Block) > 0 {
		fmt.Fprintf(&b, "block drop out %s%son ! lo0 inet from any to <%s>\n", logKeyword, quick, blockTable)
	}
	if len(r.DNSServers) > 0 {
		fmt.Fprintf(&b, "block drop out %s%son ! lo0 inet proto { tcp udp } from any to <%s> port 53\n", logKeyword, quick, dnsTable)
	}
	if !r.Strict {
		b.WriteString(passRule)
	}

	return []byte(b.String())
}

func table(name string, entries []string) string {
	if len(entries) == 0 {
		return ""
	}
	return fmt.Sprintf("table <%s> persist { %s }\n", name, strings.Join(entries, ", "))
}

// Apply загружает правила в якорь pf, предварительно проверив их разбор.
//
// Без проверки кривые правила молча не загрузились бы, а в якоре осталось бы
// старое содержимое — при этом демон считал бы, что применил новое.
func (r Ruleset) Apply(pf pfctl.Controller) error {
	rules := r.Rules()
	if err := pf.CheckAnchor(Anchor, rules); err != nil {
		return fmt.Errorf("rules do not parse in pf, nothing applied: %w", err)
	}
	return pf.LoadAnchor(Anchor, rules)
}

// KillStates сбрасывает открытые соединения к блокируемым сетям.
func (r Ruleset) KillStates(pf pfctl.Controller) error {
	var errs []string
	for _, cidr := range r.Block {
		if err := pf.KillStates(cidr); err != nil {
			errs = append(errs, err.Error())
		}
	}
	if len(errs) > 0 {
		return fmt.Errorf("state flush: %s", strings.Join(errs, "; "))
	}
	return nil
}

// Installed сообщает, загружены ли правила в якорь и вызывается ли якорь из главного набора.
func Installed(pf pfctl.Controller) (anchorLoaded, referenced bool, err error) {
	rules, err := pf.AnchorRules(Anchor)
	if err != nil {
		return false, false, err
	}
	referenced, err = pfctl.AnchorReferenced(pf, Anchor)
	if err != nil {
		return false, false, err
	}
	// Пустой вывод означает, что правил в якоре нет: комментарии pfctl не печатает.
	// Проверять подстроку «block drop out» нельзя — при mode=off или конфиге
	// только с block_dns таких правил нет, а якорь при этом применён корректно.
	return strings.TrimSpace(rules) != "", referenced, nil
}

func publicOnly(subnets []string) []string {
	var out []string
	for _, s := range subnets {
		p, err := netip.ParsePrefix(s)
		if err != nil {
			continue
		}
		if !p.Addr().IsPrivate() && !p.Addr().IsLoopback() && !p.Addr().IsLinkLocalUnicast() {
			out = append(out, s)
		}
	}
	return out
}

func dedupe(in []string) []string {
	seen := make(map[string]struct{}, len(in))
	var out []string
	for _, s := range in {
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}
